apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 535597585675.dkr.ecr.ap-northeast-2.amazonaws.com/app-ecr:1.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-creds
